// Central config — mirrors the AppConfig pattern used across FSF projects.
// With no ANTHROPIC_API_KEY set, Foundry runs fully in MOCK mode (simulated
// agent output) so the whole pipeline is demoable offline. Set the key to go live.

const API_KEY = process.env.ANTHROPIC_API_KEY || '';

module.exports = {
  PORT: parseInt(process.env.FOUNDRY_PORT || '4980', 10),
  MODEL: process.env.FOUNDRY_MODEL || 'claude-fable-5',
  API_KEY,
  MOCK_MODE: process.env.FOUNDRY_MOCK === '1' || !API_KEY,
  MAX_TOKENS: 4096,
  // Site/product builds need much more room — complete interactive apps and
  // multi-page sites regularly run past 16k output tokens (dense CSS/JS is
  // ~2.2 chars/token). Jupiter's external API caps at 32000.
  BUILD_MAX_TOKENS: 30000,
  // Jupiter — the AI-employee platform that executes/simulates Foundry's tasks.
  // Every mock-mode task is delegated to Jupiter's external API (full audit
  // trail + usage tracking there); if Jupiter is unreachable Foundry falls
  // back to its built-in simulator. Disable with FOUNDRY_JUPITER=0.
  JUPITER_URL: process.env.FOUNDRY_JUPITER_URL || 'http://localhost:3000',
  // Service-account bearer token for Jupiter's external API. Generated by
  // Jupiter's scripts/setup-external-account.ts into this app's .env; without
  // it Jupiter answers 401 and Foundry falls back to its local simulator.
  JUPITER_TOKEN: process.env.FOUNDRY_JUPITER_TOKEN || '',
  JUPITER_ENABLED: process.env.FOUNDRY_JUPITER !== '0',
  // Big product/site builds stream up to 30k output tokens — allow 10 minutes
  JUPITER_TIMEOUT_MS: 600000,
  // Autopilot: how often the orchestrator ticks (processes tasks / advances stages)
  TICK_MS: 4000,
  // Max tasks executed per tick across the whole portfolio
  TASKS_PER_TICK: 3,
  // Operate-stage: stop generating new ops tasks after this many per company
  MAX_OPS_TASKS: 12,
};
